// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebMvcReiDoAlmoco;

namespace WebMvcDoAlmoco.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebMvcDoAlmoco.Models.Candidato", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Id");

                    b.Property<string>("Nome");

                    b.HasKey("Email");

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("WebMvcDoAlmoco.Models.Votacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<int>("TotalVoto");

                    b.HasKey("Id");

                    b.ToTable("Votacao");
                });

            modelBuilder.Entity("WebMvcDoAlmoco.Models.VotoCandidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CandidatoEmail");

                    b.Property<int?>("VotacaoId");

                    b.Property<int>("Voto");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoEmail");

                    b.HasIndex("VotacaoId");

                    b.ToTable("CandidatoVotacao");
                });

            modelBuilder.Entity("WebMvcDoAlmoco.Models.VotoCandidato", b =>
                {
                    b.HasOne("WebMvcDoAlmoco.Models.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoEmail");

                    b.HasOne("WebMvcDoAlmoco.Models.Votacao")
                        .WithMany("ListaCandidato")
                        .HasForeignKey("VotacaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
